#! /bin/sh

# system configs
check_cmd() {
	command -v "$1" 2>/dev/null
}

if check_cmd apt-get; then # FOR DEB SYSTEMS
	# polkit
	mate-polkit &

elif check_cmd dnf; then # FOR RPM SYSTEMS
	# polkit
	lxpolkit &

elif check_cmd zypper; then # FOR OpenSuse SYSTEMS
	# polkit
	# mate-polkit &
	/usr/libexec/polkit-mate-authentication-agent-1 &

else
	echo "Not able to identify the system" >~/bspwm.log
fi

# # Audio widget
# pasystray &

# Network
nm-applet &

# Enable num lock
xdotool key --clearmodifiers Num_Lock &

# Hot Corner
# xdotool behave_screen_edge --quiesce 600 --delay 0 top-left exec $HOME/.config/rofi/scripts/rofi-hotcorner.sh &

# Notifications
dunst --config ~/.config/dunst/dunstrc &

# Top padding
bspc config top_padding 30

# Monitor setup
xrandr --output HDMI-2 --right-of DP-2
xrandr --output DP-2 --primary
bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor HDMI-2 -d 11 22 33 44 55
# Focus on first screen on boot
bspc desktop --focus 11 && bspc desktop --focus 1 &

# Setup resolution
xrandr --output HDMI-2 --mode 2560x1440 -r 143.91 &
xrandr --output DP-2 --mode 2560x1440 -r 143.91 &

bspc config border_width 2
bspc config window_gap 12
bspc config focused_border_color \#21F689

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a guake state=floating
bspc rule -a Guake state=floating
bspc rule -a dev.warp.Warp state=floating
bspc rule -a Yad state=floating
bspc rule -a yad-calendar state=floating
bspc rule -a gnome-calendar state=floating
bspc rule -a copyq state=floating center=on rectangle=800x600+0+0

# Startups
# picom --experimental-backend &
picom -b
pgrep -x sxhkd >/dev/null || sxhkd &
kdeconnectd &
kdeconnect-indicator &
#insync start --no-daemon &
# feh --bg-scale ~/Pictures/background &
nitrogen --restore &
/usr/bin/1password --silent &
flatpak run com.core447.StreamController -b &
flatpak run com.github.hluk.copyq &
xsetroot -cursor_name left_ptr & # Fix mouse with X
$HOME/.dotfiles/xcape/xcape.sh &
sleep 3
$HOME/.config/polybar/launch.sh &

# #session
# $HOME/.config/bspwm/scripts/rtm-startup-session.sh &
