# Window Manager Behavior & Miscellaneous settings

# Overview Setting
hotarea_size=10
enable_hotarea=1
ov_tab_mode=0
overviewgappi=5
overviewgappo=30

# Window Manager Behavior
no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=1
idleinhibit_ignore_visible=0
sloppyfocus=1
warpcursor=1
focus_cross_monitor=0
focus_cross_tag=0
enable_floating_snap=0
snap_distance=30
cursor_size=24
drag_tile_to_tile=1

# Scratchpad Settings
scratchpad_cross_monitor=1
scratchpad_width_ratio=0.9
scratchpad_height_ratio=0.9
