# Input device settings (keyboard, mouse, trackpad)

# Keyboard settings
repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=us

# Trackpad settings
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=0
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1

# Mouse settings
mouse_natural_scrolling=0
