# Layout Settings

# Scroller Layout Setting
scroller_structs=10                     # Side padding width when window ratio is 1.0
scroller_default_proportion=0.5         # Default width proportion for new windows
scroller_focus_center=0                 # Keep the active window centered (1=enable)
scroller_prefer_center=0                # Center window only if it was outside view
scroller_prefer_overspread=1            # Spread windows across space if available
edge_scroller_pointer_focus=0           # Focus windows near screen edge (1=enable)
scroller_ignore_proportion_single=0     # Disable width proportion adjustment for single windows (1=ignore)
scroller_default_proportion_single=1.0  # Default width proportion for single windows
scroller_proportion_preset=0.5,1.0      # Preset widths for cycling window sizes

# Master-Stack Layout Setting
new_is_master=1      # Open new windows in the master slot
default_mfact=0.55   # Default split ratio between master/stack
default_nmaster=1    # Number of master windows
smartgaps=0          # Hide window gaps when only one window is visible

# Layout Support / Workspace Rules
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller
