# Autostart applications
exec-once=waybar -c ~/.dotfiles/mangowm/waybar/config.jsonc -s ~/.dotfiles/mangowm/waybar/style.css
exec-once=awww-daemon
exec-once=/usr/libexec/polkit-mate-authentication-agent-1
#exec-once=hypridle
exec-once=nm-applet
exec-once=mako
exec-once=kdeconnectd
exec-once=kdeconnect-indicator
exec-once=rm -rf ~/.config/vivaldi/Singleton*
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=/usr/bin/1password --silent
exec-once=~/.dotfiles/mangowm/scripts/mouse_actions.py
exec-once=waybar -c ~/.dotfiles/mangowm/waybar/trigger_config.jsonc -s ~/.dotfiles/mangowm/waybar/trigger_style.css
#exec-once=~/.config/hypr/scripts/launch-kitty-magic.sh
#exec-once=~/.config/hypr/scripts/watchdog.sh
exec-once=~/.QS-Launcher/spotlight
exec-once=~/.dotfiles/mangowm/waybar/scripts/waybar_indicator_watcher.sh
