# Autostart applications
exec-once=waybar
exec-once=awww-daemon
exec-once=/usr/libexec/polkit-mate-authentication-agent-1
#exec-once=hypridle
exec-once=nm-applet
exec-once=mako
exec-once=kdeconnectd
exec-once=kdeconnect-indicator
exec-once=rm -rf ~/.config/vivaldi/Singleton*
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=/usr/bin/1password --silent
#exec-once=~/.config/hypr/scripts/launch-kitty-magic.sh
#exec-once=~/.dotfiles/hyprland/hypr/scripts/mouse_actions.py
#exec-once=~/.config/hypr/scripts/watchdog.sh
#exec-once=~/.QS-Launcher/spotlight
#exec-once=~/.config/waybar/scripts/waybar_indicator_watcher.sh
