# Window effects & decorations
blur=1
blur_layer=1
blur_optimized=1
blur_params_num_passes = 2
blur_params_radius = 5
blur_params_noise = 0.02
blur_params_brightness = 0.9
blur_params_contrast = 0.9
blur_params_saturation = 1.2

shadows = 0
layer_shadows = 0
shadow_only_floating = 1
shadows_size = 10
shadows_blur = 15
shadows_position_x = 0
shadows_position_y = 0
shadowscolor= 0x000000ff

border_radius=6
no_radius_when_single=0
focused_opacity=1.0
unfocused_opacity=1.0

# Animation Configuration (support type: zoom, slide)
# tag_animation_direction: 1-horizontal, 0-vertical
# Enable animations
animations=1
layer_animations=1

# Animation types
animation_type_open=zoom
animation_type_close=zoom

# Fade effects
animation_fade_in=1
animation_fade_out=1
fadein_begin_opacity=0.5
fadeout_begin_opacity=0.8

# Tag animation
tag_animation_direction=1

# Zoom parameters
zoom_initial_ratio=0.3
zoom_end_ratio=0.8

# Durations (milliseconds)
animation_duration_open=400
animation_duration_close=500
animation_duration_move=500
animation_duration_tag=350
animation_duration_focus=0

# Bezier curves
animation_curve_open=0.46,1.0,0.29,1
animation_curve_close=0.08,0.92,0,1
animation_curve_move=0.46,1.0,0.29,1
animation_curve_tag=0.46,1.0,0.29,1
animation_curve_focus=0.46,1.0,0.29,1
animation_curve_opafadeout=0.5,0.5,0.5,0.5
animation_curve_opafadein=0.46,1.0,0.29,1

# Appearance, Gaps & Colors
gappih=5
gappiv=5
gappoh=15
gappov=15
borderpx=2
rootcolor=0x201b14ff
bordercolor=0x646464ff
focuscolor=0x78ffb4ff
maximizescreencolor=0x89aa61ff
urgentcolor=0xad401fff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff

# Add blur to apps
## Nautilkus
windowrule=focused_opacity:0.95,appid:Nautilus
windowrule=unfocused_opacity:0.8,appid:Nautilus

## Vscode
windowrule=focused_opacity:0.98,appid:code
windowrule=unfocused_opacity:0.9,appid:code

## Vscode
windowrule=focused_opacity:0.98,appid:antigravity
windowrule=unfocused_opacity:0.9,appid:antigravity
