# Add blur to apps
## Nautilkus
windowrule=focused_opacity:0.95,appid:Nautilus
windowrule=unfocused_opacity:0.8,appid:Nautilus

## Vscode
windowrule=focused_opacity:0.98,appid:code
windowrule=unfocused_opacity:0.9,appid:code

## Vscode
windowrule=focused_opacity:0.98,appid:antigravity
windowrule=unfocused_opacity:0.9,appid:antigravity

# Screenshot app rules
layerrule=noanim:1,noblur:1,layer_name:selection
windowrule=isfloating:1,appid:swappy

# Screenshot app rules
layerrule=noanim:1,noblur:1,layer_name:selection
windowrule=isfloating:1,appid:flameshot