#!/bin/bash

numberOfDesktops=$(wmctrl -d | wc -l)
firstdesktop=$((wmctrl -d |head -n 1|awk '{print $1}' + 1))
currentDesktop=$(qdbus org.kde.KWin /KWin currentDesktop)
previousDesktop=$((currentDesktop - 1))

if [[ $currentDesktop = $firstdesktop ]]; then
    exit
elif [[ $currentDesktop = "$numberOfDesktops" ]]; then
    qdbus org.kde.KWin /KWin setCurrentDesktop 1
else
    qdbus org.kde.KWin /KWin setCurrentDesktop $previousDesktop
fi
