#!/bin/bash

# check cmd function
check_cmd() {
    command -v "$1" > /dev/null 2> /dev/null
}

# Add the repository key with either wget or curl
if check_cmd apt-get; then # FOR DEB SYSTEMS
    aptdcon --refresh 2> /dev/null
    APT_CHECK=`apt list --silent -q  --upgradeable > /tmp/packages-upgradeable 2> /dev/null`
        FILE=/tmp/packages-upgradeable
        if test -f "$FILE"; then
            APT_LIST=`cat /tmp/packages-upgradeable |wc -l`
            echo " $APT_LIST"
            # echo " `apt-get dist-upgrade -s --quiet=2 | grep ^Inst | wc -l`"
        else
            echo " 0"
        fi

    rm -rf /tmp/packages-upgradeable

elif check_cmd dnf; then  # FOR RPM SYSTEMS
    DNF_CHECK=`dnf check-update -y -q |wc -l |grep -Eo '[0-9]{1,6}'`
    echo " $DNF_CHECK"

elif check_cmd zypper; then  # FOR RPM SYSTEMS
    ZYPPER_CHECK=`zypper list-updates |wc -l |grep -Eo '[0-9]{1,6}'`
    echo " $ZYPPER_CHECK"

else
    echo "Not able to identify the system"
    exit 0
fi



