#! /bin/sh


# Startups
$HOME/.config/polybar/launch.sh &
picom --experimental-backend &
pgrep -x sxhkd > /dev/null || sxhkd &
guake &
# feh --bg-scale ~/Pictures/background &
nitrogen --restore &
xsetroot -cursor_name left_ptr & # Fix mouse with X
$HOME/GIT-REPOS/workstation/desktop/source/any/config/xcape/xcape.sh &

# # Network
nm-applet &

# Enable num lock
xdotool key --clearmodifiers Num_Lock &

# Notifications
dunst --config ~/.config/dunst/dunstrc &

# Monitor setup
# bspc monitor DisplayPort-0 -d 1 2 3 4 5
# bspc monitor HDMI-A-0 -d 6 7 8 9 10

# Monitor setup
bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 11 22 33 44 55

# Focus on first screen on boot
bspc desktop --focus 11 && bspc desktop --focus 1 &


# Setup resolution
xrandr --output DisplayPort-0 --mode 2560x1440 -r 143.91 &

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color \#21F689


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a guake state=floating
bspc rule -a Guake state=floating
bspc rule -a Yad state=floating
bspc rule -a yad-calendar state=floating


# #session
# $HOME/.config/bspwm/scripts/rtm-startup-session.sh &