-- Monitor configuration
-- Generated by nwg-displays layout: DP-1 left, HDMI-A-1 right

hl.monitor({ output = "DP-1",     mode = "2560x1440@120", position = "0x0",    scale = 1.0 })
hl.monitor({ output = "HDMI-A-1", mode = "2560x1440@120", position = "2560x0", scale = 1.0 })
