#! /bin/sh


# Startups
$HOME/.config/polybar/launch.sh &
picom --experimental-backend &
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/GIT-REPOS/workstation/desktop/utils/bspwm/config/xcape/xcape.sh
guake &
feh --bg-scale ~/Pictures/background &
xsetroot -cursor_name left_ptr & # Fix mouse with X

# Monitor setup
bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a guake state=floating
bspc rule -a Guake state=floatingz