#!/bin/bash

# check cmd function
check_cmd() {
    command -v "$1" > /dev/null 2> /dev/null
}

# Add the repository key with either wget or curl
if check_cmd apt-get; then # FOR DEB SYSTEMS
    APT_CHECK=`apt-get -s upgrade | grep -iP '^\d+ upgraded' | cut -d' ' -f1`
    echo " $APT_CHECK"

elif check_cmd dnf; then  # FOR RPM SYSTEMS
    DNF_CHECK=`dnf check-update -y -q |wc -l |grep -Eo '[0-9]{1,6}'`
    echo " $DNF_CHECK"

elif check_cmd zypper; then  # FOR RPM SYSTEMS
    ZYPPER_CHECK=`zypper list-updates |wc -l |grep -Eo '[0-9]{1,6}'`
    echo " $ZYPPER_CHECK"

else
    echo "Not able to identify the system"
    exit 0
fi



