[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']
rotate-video-lock-static=['<Super>o', 'XF86RotationLockToggle']

[custom-keybindings/custom0]
binding='<Shift><Control><Alt>F7'
command='rofiiiiiiiii'
name='rofi'
