[/]
maximize=['<Super>Up']
move-to-monitor-down=['<Super><Shift>Down']
move-to-monitor-left=['<Super><Shift>Left']
move-to-monitor-right=['<Super><Shift>Right']
move-to-monitor-up=['<Super><Shift>Up']
move-to-workspace-down=['<Control><Shift><Alt>Down']
move-to-workspace-left=['<Shift><Control><Super>Left']
move-to-workspace-right=['<Shift><Control><Super>Right']
move-to-workspace-up=['<Control><Shift><Alt>Up']
switch-applications=['<Super>Tab', '<Alt>Tab']
switch-applications-backward=['<Shift><Super>Tab', '<Shift><Alt>Tab']
switch-group=['<Super>Above_Tab', '<Alt>Above_Tab']
switch-group-backward=['<Shift><Super>Above_Tab', '<Shift><Alt>Above_Tab']
switch-panels=['<Control><Alt>Tab']
switch-panels-backward=['<Shift><Control><Alt>Tab']
switch-to-workspace-1=['<Super>Home']
switch-to-workspace-last=['<Super>End']
switch-to-workspace-left=['<Control><Super>Left']
switch-to-workspace-right=['<Control><Super>Right']
unmaximize=['<Super>Down', '<Alt>F5']
