[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']
play=['<Super>c']
rotate-video-lock-static=['<Super>o', 'XF86RotationLockToggle']

[custom-keybindings/custom0]
binding='<Super>e'
command='nautilus'
name='Nautilus - File Manager'

[custom-keybindings/custom1]
binding='<Super>q'
command='ydotool key 56:1 62:1 62:0 56:0'
name='Quit'

[custom-keybindings/custom2]
binding='<Control><Alt>t'
command='kitty'
name='kitty'
