[/]
attach-modal-dialogs=true
dynamic-workspaces=false
edge-tiling=true
workspaces-only-on-primary=false

[keybindings]
cancel-input-capture=['<Super><Shift>Escape']
toggle-tiled-left=['<Super>Left']
toggle-tiled-right=['<Super>Right']

[wayland/keybindings]
restore-shortcuts=['<Super>Escape']
