#! /bin/sh

# system configs
check_cmd() {
	command -v "$1" 2>/dev/null
}


# # Audio widget
# pasystray &

# Enable num lock
xdotool key --clearmodifiers Num_Lock &


# Top padding
bspc config top_padding 30

# Monitor setup
bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor DP-2 -d 11 22 33 44 55

# Focus on first screen on boot
bspc desktop --focus 11 && bspc desktop --focus 1 &

# Setup resolution
xrandr --output DP-1 --mode 2560x1440 -r 143.91 &
xrandr --output DP-2 --mode 2560x1440 -r 143.91 &

bspc config border_width 2
bspc config window_gap 12
bspc config focused_border_color \#21F689

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a guake state=floating
bspc rule -a Guake state=floating
bspc rule -a Yad state=floating
bspc rule -a yad-calendar state=floating
bspc rule -a gnome-calendar state=floating

# Startups
# picom --experimental-backend &
picom --animations -b
pgrep -x sxhkd >/dev/null || sxhkd &
kdeconnect-indicator &
/usr/bin/1password --silent &
streamdeck -n &
$HOME/.dotfiles/xcape/xcape.sh &
sleep 3
# $HOME/.config/bspwm/scripts/rtm-startup-session.sh &
