#!/usr/bin/env bash

# Available Styles
# >> Created and tested on : rofi 1.6.0-1
#
# column_circle     column_square     column_rounded     column_alt
# card_circle     card_square     card_rounded     card_alt
# dock_circle     dock_square     dock_rounded     dock_alt
# drop_circle     drop_square     drop_rounded     drop_alt
# full_circle     full_square     full_rounded     full_alt
# row_circle      row_square      row_rounded      row_alt


restart_dwm() {
    cur=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print log($3)/log(2)+1}')
    kill -HUP $(pidof -s dwm) && xdotool key Super_L
    (sleep 0.1 && xdotool key "Super_L+$cur")
}

[[ $1 = "restart" ]] && restart_dwm && exit

theme="card_alt"
dir="/home/rtm/GIT-REPOS/REPOS/ft-labs/phyOS-system-scripts/usr/share/phyos/util-scripts/powermenu"
pOS-powermenutitle &

# random colors
styles=($(ls -p --hide="colors.rasi" $dir/styles))
color="${styles[$(( 3 ))]}"

# comment this line to disable random colors
# sed -i -e "s/@import .*/@import \"$color\"/g" $dir/styles/colors.rasi

# comment these lines to disable random style
#themes=($(ls -p --hide="powermenu.sh" --hide="styles" --hide="confirm.rasi" --hide="message.rasi" $dir))
#theme="${themes[$(( $RANDOM % 24 ))]}"

uptime=$(uptime -p | sed -e 's/up //g')

rofi_command="rofi -theme /home/rtm/GIT-REPOS/REPOS/ft-labs/.config/rofi/config.rasi.sync"

# Options
shutdown=""
reboot="ﰇ"
lock=""
logout="﫼"
renew_dwm=""

case "$(readlink -f /sbin/init)" in
	*systemd*) ctl='systemctl' ;;
	*) ctl='loginctl' ;;
esac

# Variable passed to rofi
options="$logout\n$lock\n$shutdown\n$reboot\n$renew_dwm"

chosen="$(echo -e "$options" | $rofi_command -p "Uptime: $uptime" -dmenu -selected-row 2)"
case $chosen in
    $logout)
        killall -9 pOS-powermenutitle && dunstctl close-all
		kill -TERM $(pidof -s dwm) && xdotool key Super_L ;;
    $lock)
        killall -9 pOS-powermenutitle && dunstctl close-all
        if pacman -Qq "lightdm" > /dev/null ; then
            dm-tool lock &
        else
            betterlockscreen -l &
        fi ;;
    $shutdown)
        killall -9 pOS-powermenutitle && dunstctl close-all
		$ctl poweroff -i ;;
    $reboot)
        killall -9 pOS-powermenutitle && dunstctl close-all
		$ctl reboot -i ;;
	$renew_dwm)
        killall -9 pOS-powermenutitle && dunstctl close-all
        restart_dwm ;;
    *)
        killall -9 pOS-powermenutitle && dunstctl close-all ;;
esac
